# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_ID', models.CharField(max_length=55, verbose_name='Admission ID')),
                ('Patient_ID', models.CharField(max_length=55, verbose_name='Patient ID')),
                ('Patient_Name', models.CharField(blank=True, max_length=55, null=True, verbose_name='Patient Name')),
                ('Treatment_ID', models.CharField(blank=True, max_length=55, null=True, verbose_name='Treatment ID')),
                ('Ward_ID', models.CharField(blank=True, max_length=55, null=True, verbose_name='Ward ID')),
                ('Details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Details')),
                ('Date_Of_Admission', models.DateTimeField(verbose_name='Date Time Field')),
            ],
            options={
                'verbose_name': 'ADMISSION',
                'verbose_name_plural': 'ADMISSIONS',
            },
        ),
    ]
