# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(blank=True, max_length=55, null=True, verbose_name='User_Name')),
                ('Password', models.CharField(blank=True, max_length=40, null=True, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'SIGNOUT',
                'verbose_name_plural': 'SIGNOUTS',
            },
        ),
    ]
