# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.CharField(blank=True, max_length=55, null=True, verbose_name='Patient ID')),
                ('Patient_Name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Patient Name')),
                ('Gender', models.CharField(max_length=1, verbose_name='Gender (F or M )')),
                ('Home_Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home Address')),
                ('Date_Of_Appointment', models.DateTimeField(verbose_name='Date of Appointment')),
                ('Email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('Treatment_ID', models.CharField(blank=True, max_length=55, null=True, verbose_name='Treatment ID')),
            ],
            options={
                'verbose_name': 'APPOINTMENT',
                'verbose_name_plural': 'APPOINTMENTS',
            },
        ),
    ]
