# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Gender',
            field=models.CharField(max_length=1, verbose_name='Gender(F or M )'),
        ),
    ]
