# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(blank=True, max_length=55, null=True, verbose_name='User ID')),
                ('User_Name', models.CharField(blank=True, max_length=55, null=True, verbose_name='User Name')),
                ('Password', models.CharField(max_length=55, verbose_name='Password ')),
                ('Gender', models.CharField(max_length=1, verbose_name='Gender(M or F)')),
                ('Home_Address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Home Dddress')),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('Contact_Number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
            ],
            options={
                'verbose_name': 'USER',
                'verbose_name_plural': 'USERS',
            },
        ),
    ]
